# Broadcasting in Python (C1W2L15)

import numpy as np
vector = np.arange(5)
vector = vector.reshape(5, 1)
print("vector :")
print(vector)
print("vector + 100 :")
print(vector + 100)
print("__________________________________________________________________________________")

matrix1 = np.arange(1,11)
matrix1 = matrix1.reshape(2, 5)
matrix2 = np.array([100, 110, 120, 130, 140])
print("matrix1:")
print(matrix1)
print("matrix2:")
print(matrix2)
print("matrix1+matrix2: ")
print(matrix1+matrix2)
print("__________________________________________________________________________________")
matrix1 = np.arange(1,11)
matrix1 = matrix1.reshape(2, 5)
matrix2 = np.array([[100], [200]])
print("matrix1:")
print(matrix1)
print("matrix2:")
print(matrix2)
print("matrix1+matrix2: ")
print(matrix1+matrix2)